project:
  type: website

website:
  title: "Ryan Safner"
  site-url: "https://ryansafner.com"
  description: "Personal website of Dr. Ryan Safner"
  google-analytics: "UA-12760297-1"
  favicon: "me2023.jpg"
  twitter-card:
    image: "me2023.jpg"
    creator: "@ryansafner"
  open-graph:
    image: "me2023.jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.pdf
        text: CV
      - teaching.qmd
      - research.qmd
      - software.qmd
      - blog.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    include-in-header:
      - includes.html
      
editor: visual

