<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>R For Econometrics: A Modest Handbook</title>
  <meta name="description" content="This is a simple guide intended for my ECON 480 - Econometrics students at Hood College.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="R For Econometrics: A Modest Handbook" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a simple guide intended for my ECON 480 - Econometrics students at Hood College." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="R For Econometrics: A Modest Handbook" />
  
  <meta name="twitter:description" content="This is a simple guide intended for my ECON 480 - Econometrics students at Hood College." />
  

<meta name="author" content="Ryan Safner (safner@hood.edu)">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="regression-basics.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for Econometrics: A Modest Handbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how-to-read-this-guide"><i class="fa fa-check"></i><b>1.1</b> How to Read this Guide</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Basics</a><ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#operating-r-studio"><i class="fa fa-check"></i><b>2.1</b> Operating R Studio</a><ul>
<li class="chapter" data-level="2.1.1" data-path="basics.html"><a href="basics.html#keyboard-shortcuts"><i class="fa fa-check"></i><b>2.1.1</b> Keyboard Shortcuts</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#Working-directory"><i class="fa fa-check"></i><b>2.2</b> Working Directory (<code>wd</code>)</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#packages"><i class="fa fa-check"></i><b>2.3</b> Packages</a></li>
<li class="chapter" data-level="2.4" data-path="basics.html"><a href="basics.html#useful-packages"><i class="fa fa-check"></i><b>2.4</b> Useful Packages</a></li>
<li class="chapter" data-level="2.5" data-path="basics.html"><a href="basics.html#calculations"><i class="fa fa-check"></i><b>2.5</b> Calculations</a></li>
<li class="chapter" data-level="2.6" data-path="basics.html"><a href="basics.html#hints-for-writing-code"><i class="fa fa-check"></i><b>2.6</b> Hints for Writing Code</a><ul>
<li class="chapter" data-level="2.6.1" data-path="basics.html"><a href="basics.html#naming-objects"><i class="fa fa-check"></i><b>2.6.1</b> Naming Objects</a></li>
<li class="chapter" data-level="2.6.2" data-path="basics.html"><a href="basics.html#commenting"><i class="fa fa-check"></i><b>2.6.2</b> Commenting</a></li>
<li class="chapter" data-level="2.6.3" data-path="basics.html"><a href="basics.html#managing-your-workflow"><i class="fa fa-check"></i><b>2.6.3</b> Managing Your Workflow</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="basics.html"><a href="basics.html#getting-help"><i class="fa fa-check"></i><b>2.7</b> Getting Help</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="objects.html"><a href="objects.html"><i class="fa fa-check"></i>Objects</a><ul>
<li class="chapter" data-level="2.8" data-path="objects.html"><a href="objects.html#vectors"><i class="fa fa-check"></i><b>2.8</b> Vectors</a><ul>
<li class="chapter" data-level="2.8.1" data-path="objects.html"><a href="objects.html#functions"><i class="fa fa-check"></i><b>2.8.1</b> Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="other-object-types.html"><a href="other-object-types.html"><i class="fa fa-check"></i><b>3</b> Other Object Types</a><ul>
<li class="chapter" data-level="3.1" data-path="other-object-types.html"><a href="other-object-types.html#lists"><i class="fa fa-check"></i><b>3.1</b> Lists</a></li>
<li class="chapter" data-level="3.2" data-path="other-object-types.html"><a href="other-object-types.html#matrix"><i class="fa fa-check"></i><b>3.2</b> Matrix</a></li>
<li class="chapter" data-level="3.3" data-path="other-object-types.html"><a href="other-object-types.html#data-frame"><i class="fa fa-check"></i><b>3.3</b> Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-classes.html"><a href="data-classes.html"><i class="fa fa-check"></i><b>4</b> Data Classes</a><ul>
<li class="chapter" data-level="4.0.1" data-path="data-classes.html"><a href="data-classes.html#numeric"><i class="fa fa-check"></i><b>4.0.1</b> Numeric</a></li>
<li class="chapter" data-level="4.0.2" data-path="data-classes.html"><a href="data-classes.html#double"><i class="fa fa-check"></i><b>4.0.2</b> Double</a></li>
<li class="chapter" data-level="4.0.3" data-path="data-classes.html"><a href="data-classes.html#logical"><i class="fa fa-check"></i><b>4.0.3</b> Logical</a></li>
<li class="chapter" data-level="4.0.4" data-path="data-classes.html"><a href="data-classes.html#character"><i class="fa fa-check"></i><b>4.0.4</b> Character</a></li>
<li class="chapter" data-level="4.0.5" data-path="data-classes.html"><a href="data-classes.html#factor"><i class="fa fa-check"></i><b>4.0.5</b> Factor</a></li>
<li class="chapter" data-level="4.1" data-path="data-classes.html"><a href="data-classes.html#checking-or-reclassifying-objects"><i class="fa fa-check"></i><b>4.1</b> Checking or Reclassifying Objects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i>Data Wrangling</a><ul>
<li class="chapter" data-level="4.2" data-path="data-wrangling.html"><a href="data-wrangling.html#packages-1"><i class="fa fa-check"></i><b>4.2</b> Packages</a></li>
<li class="chapter" data-level="4.3" data-path="data-wrangling.html"><a href="data-wrangling.html#importing-data"><i class="fa fa-check"></i><b>4.3</b> Importing Data</a></li>
<li class="chapter" data-level="4.4" data-path="data-wrangling.html"><a href="data-wrangling.html#merging-data"><i class="fa fa-check"></i><b>4.4</b> Merging Data</a></li>
<li class="chapter" data-level="4.5" data-path="data-wrangling.html"><a href="data-wrangling.html#using-the-pipe-operator"><i class="fa fa-check"></i><b>4.5</b> Using the <code>%&gt;%</code> “Pipe” Operator</a></li>
<li class="chapter" data-level="4.6" data-path="data-wrangling.html"><a href="data-wrangling.html#subsetting"><i class="fa fa-check"></i><b>4.6</b> Subsetting</a></li>
<li class="chapter" data-level="4.7" data-path="data-wrangling.html"><a href="data-wrangling.html#section"><i class="fa fa-check"></i><b>4.7</b> </a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="plotting.html"><a href="plotting.html"><i class="fa fa-check"></i><b>5</b> Plotting</a><ul>
<li class="chapter" data-level="5.1" data-path="plotting.html"><a href="plotting.html#plotting-in-base-r"><i class="fa fa-check"></i><b>5.1</b> Plotting in Base <code>R</code></a><ul>
<li class="chapter" data-level="5.1.1" data-path="plotting.html"><a href="plotting.html#histogram"><i class="fa fa-check"></i><b>5.1.1</b> Histogram</a></li>
<li class="chapter" data-level="5.1.2" data-path="plotting.html"><a href="plotting.html#boxplot"><i class="fa fa-check"></i><b>5.1.2</b> Boxplot</a></li>
<li class="chapter" data-level="5.1.3" data-path="plotting.html"><a href="plotting.html#scatterplot"><i class="fa fa-check"></i><b>5.1.3</b> Scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="plotting.html"><a href="plotting.html#with-ggplot2"><i class="fa fa-check"></i><b>5.2</b> With <code>ggplot2</code></a><ul>
<li class="chapter" data-level="5.2.1" data-path="plotting.html"><a href="plotting.html#two-ways-to-plot"><i class="fa fa-check"></i><b>5.2.1</b> Two Ways to Plot</a></li>
<li class="chapter" data-level="5.2.2" data-path="plotting.html"><a href="plotting.html#two-ways-to-plot-ii"><i class="fa fa-check"></i><b>5.2.2</b> Two Ways to Plot II</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regression-basics.html"><a href="regression-basics.html"><i class="fa fa-check"></i><b>6</b> Regression Basics</a><ul>
<li class="chapter" data-level="6.1" data-path="regression-basics.html"><a href="regression-basics.html#ordinary-least-squares-ols-regression"><i class="fa fa-check"></i><b>6.1</b> Ordinary Least Squares (OLS) Regression</a><ul>
<li class="chapter" data-level="6.1.1" data-path="regression-basics.html"><a href="regression-basics.html#diagnostics"><i class="fa fa-check"></i><b>6.1.1</b> Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="regression-basics.html"><a href="regression-basics.html#prediction"><i class="fa fa-check"></i><b>6.2</b> Prediction</a></li>
<li class="chapter" data-level="6.3" data-path="regression-basics.html"><a href="regression-basics.html#residual-plots"><i class="fa fa-check"></i><b>6.3</b> Residual Plots</a></li>
<li class="chapter" data-level="6.4" data-path="regression-basics.html"><a href="regression-basics.html#regression-output-table"><i class="fa fa-check"></i><b>6.4</b> Regression Output Table</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-regression.html"><a href="advanced-regression.html"><i class="fa fa-check"></i><b>7</b> Advanced Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="advanced-regression.html"><a href="advanced-regression.html#multivariate-regression"><i class="fa fa-check"></i><b>7.1</b> Multivariate Regression</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-regression.html"><a href="advanced-regression.html#dummy-variables"><i class="fa fa-check"></i><b>7.2</b> Dummy Variables</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-regression.html"><a href="advanced-regression.html#polynomial-regression"><i class="fa fa-check"></i><b>7.3</b> Polynomial Regression</a><ul>
<li class="chapter" data-level="7.3.1" data-path="advanced-regression.html"><a href="advanced-regression.html#higher-polynomials"><i class="fa fa-check"></i><b>7.3.1</b> Higher Polynomials</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="advanced-regression.html"><a href="advanced-regression.html#logarithmic-models"><i class="fa fa-check"></i><b>7.4</b> Logarithmic Models</a></li>
<li class="chapter" data-level="7.5" data-path="advanced-regression.html"><a href="advanced-regression.html#standardizing-variables"><i class="fa fa-check"></i><b>7.5</b> Standardizing Variables</a></li>
<li class="chapter" data-level="7.6" data-path="advanced-regression.html"><a href="advanced-regression.html#panel-data"><i class="fa fa-check"></i><b>7.6</b> Panel Data</a><ul>
<li class="chapter" data-level="7.6.1" data-path="advanced-regression.html"><a href="advanced-regression.html#two-way-fixed-effects"><i class="fa fa-check"></i><b>7.6.1</b> Two Way Fixed Effects</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://ryansafner.com" target="blank">Ryan Safner</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R For Econometrics: A Modest Handbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="advanced-regression" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Advanced Regression</h1>
<div id="multivariate-regression" class="section level2">
<h2><span class="header-section-number">7.1</span> Multivariate Regression</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1</span>)
x&lt;-<span class="kw">rnorm</span>(<span class="dv">500</span>,<span class="dv">10</span>,<span class="dv">2</span>)
z&lt;-<span class="kw">runif</span>(<span class="dv">500</span>,<span class="dv">10</span>,<span class="dv">20</span>)
y&lt;-<span class="kw">rnorm</span>(<span class="dv">500</span>,<span class="dv">2</span><span class="op">*</span>x<span class="op">*</span>z,<span class="dv">2</span>)
year&lt;-<span class="kw">sample</span>(<span class="kw">seq</span>(<span class="dv">2000</span>,<span class="dv">2018</span>,<span class="dv">1</span>),<span class="dv">500</span>,<span class="dt">replace=</span><span class="ot">TRUE</span>)

<span class="co"># generate categorical variables</span>

<span class="co"># make a shape variable </span>
shapes&lt;-<span class="kw">c</span>(<span class="st">&quot;square&quot;</span>,<span class="st">&quot;circle&quot;</span>,<span class="st">&quot;triangle&quot;</span>,<span class="st">&quot;rectangle&quot;</span>,<span class="st">&quot;trapezoid&quot;</span>)
shape&lt;-<span class="kw">sample</span>(shapes,<span class="dv">500</span>,<span class="dt">replace=</span><span class="ot">TRUE</span>) <span class="co"># sample 500 random draws with replacement from shapes</span>

<span class="co"># make a region variable </span>
regions&lt;-<span class="kw">c</span>(<span class="st">&quot;north&quot;</span>,<span class="st">&quot;south&quot;</span>,<span class="st">&quot;east&quot;</span>,<span class="st">&quot;west&quot;</span>)
region&lt;-<span class="kw">sample</span>(regions,<span class="dv">500</span>,<span class="dt">replace=</span><span class="ot">TRUE</span>) <span class="co"># sample 500 random draws with replacement from regions</span>

<span class="co"># make a dummy variable </span>
yes&lt;-<span class="kw">sample</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="dv">500</span>,<span class="dt">replace=</span><span class="ot">TRUE</span>) 

<span class="co"># combine into dataframe called df</span>

df&lt;-<span class="kw">data.frame</span>(<span class="dt">x=</span>x,
               <span class="dt">y=</span>y,
               <span class="dt">z=</span>z,
               <span class="dt">shape=</span><span class="kw">factor</span>(shape),
               <span class="dt">region=</span><span class="kw">factor</span>(region),
               <span class="dt">yes=</span>yes,
               <span class="dt">year=</span><span class="kw">factor</span>(year))

<span class="co"># look at new df</span>

<span class="kw">head</span>(df)</code></pre></div>
<pre><code>##           x        y        z     shape region yes year
## 1  8.747092 264.8931 15.30809 trapezoid   east   0 2009
## 2 10.367287 347.6574 16.84861  triangle   west   1 2001
## 3  8.328743 227.9193 13.83283    square   east   0 2016
## 4 13.190562 517.0824 19.54988    circle   east   0 2008
## 5 10.659016 235.8301 11.18357 trapezoid  north   1 2018
## 6  8.359063 169.6481 10.39100 trapezoid   west   0 2009</code></pre>
<p>It is quite simply to simply add additional covariates to a regression. In the <code>lm</code> object, we add variables with <code>+</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg1&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>z, <span class="dt">data=</span>df)
<span class="kw">summary</span>(reg1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + z, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.969  -5.115  -0.013   5.756  42.078 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -295.7258     3.7549  -78.76   &lt;2e-16 ***
## x             29.4336     0.2671  110.19   &lt;2e-16 ***
## z             20.1389     0.1849  108.94   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.05 on 497 degrees of freedom
## Multiple R-squared:  0.9809, Adjusted R-squared:  0.9808 
## F-statistic: 1.277e+04 on 2 and 497 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="dummy-variables" class="section level2">
<h2><span class="header-section-number">7.2</span> Dummy Variables</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_d&lt;-<span class="kw">lm</span>(y<span class="op">~</span>yes, <span class="dt">data=</span>df)
<span class="kw">summary</span>(reg_d)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ yes, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -199.739  -65.966   -8.196   64.445  272.577 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  296.881      5.324  55.767   &lt;2e-16 ***
## yes            2.588      7.815   0.331    0.741    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 87.15 on 498 degrees of freedom
## Multiple R-squared:  0.0002202,  Adjusted R-squared:  -0.001787 
## F-statistic: 0.1097 on 1 and 498 DF,  p-value: 0.7406</code></pre>
<p>The effect on <code>y</code> of going from “No” to “Yes” is 2.59.</p>
<p>If we wanted to make a dummy variable for an existing categorical variable</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>north&lt;-<span class="kw">ifelse</span>(region<span class="op">==</span><span class="st">&quot;north&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>)
df<span class="op">$</span>south&lt;-<span class="kw">ifelse</span>(region<span class="op">==</span><span class="st">&quot;south&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>)
df<span class="op">$</span>east&lt;-<span class="kw">ifelse</span>(region<span class="op">==</span><span class="st">&quot;east&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>)
df<span class="op">$</span>west&lt;-<span class="kw">ifelse</span>(region<span class="op">==</span><span class="st">&quot;west&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>)

<span class="kw">head</span>(df)</code></pre></div>
<pre><code>##           x        y        z     shape region yes year north south east
## 1  8.747092 264.8931 15.30809 trapezoid   east   0 2009     0     0    1
## 2 10.367287 347.6574 16.84861  triangle   west   1 2001     0     0    0
## 3  8.328743 227.9193 13.83283    square   east   0 2016     0     0    1
## 4 13.190562 517.0824 19.54988    circle   east   0 2008     0     0    1
## 5 10.659016 235.8301 11.18357 trapezoid  north   1 2018     1     0    0
## 6  8.359063 169.6481 10.39100 trapezoid   west   0 2009     0     0    0
##   west
## 1    0
## 2    1
## 3    0
## 4    0
## 5    0
## 6    1</code></pre>
<p>Here is where a <code>for</code> loop also can come in handy:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">unique</span>(df<span class="op">$</span>region)){
  region[i]&lt;-<span class="kw">ifelse</span>(df<span class="op">$</span>region<span class="op">==</span>i,<span class="dv">1</span>,<span class="dv">0</span>)
}</code></pre></div>
<pre><code>## Warning in region[i] &lt;- ifelse(df$region == i, 1, 0): number of items to
## replace is not a multiple of replacement length

## Warning in region[i] &lt;- ifelse(df$region == i, 1, 0): number of items to
## replace is not a multiple of replacement length

## Warning in region[i] &lt;- ifelse(df$region == i, 1, 0): number of items to
## replace is not a multiple of replacement length

## Warning in region[i] &lt;- ifelse(df$region == i, 1, 0): number of items to
## replace is not a multiple of replacement length</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(df)</code></pre></div>
<pre><code>##           x        y        z     shape region yes year north south east
## 1  8.747092 264.8931 15.30809 trapezoid   east   0 2009     0     0    1
## 2 10.367287 347.6574 16.84861  triangle   west   1 2001     0     0    0
## 3  8.328743 227.9193 13.83283    square   east   0 2016     0     0    1
## 4 13.190562 517.0824 19.54988    circle   east   0 2008     0     0    1
## 5 10.659016 235.8301 11.18357 trapezoid  north   1 2018     1     0    0
## 6  8.359063 169.6481 10.39100 trapezoid   west   0 2009     0     0    0
##   west
## 1    0
## 2    1
## 3    0
## 4    0
## 5    0
## 6    1</code></pre>
</div>
<div id="polynomial-regression" class="section level2">
<h2><span class="header-section-number">7.3</span> Polynomial Regression</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1&lt;-<span class="kw">rnorm</span>(<span class="dv">500</span>,<span class="dv">5</span>,<span class="dv">1</span>)
y1&lt;-(x1<span class="op">-</span><span class="dv">5</span>)<span class="op">^</span><span class="dv">2</span><span class="op">+</span><span class="dv">2</span><span class="op">+</span><span class="kw">rnorm</span>(<span class="dv">500</span>,<span class="dv">1</span>,<span class="fl">0.5</span>)

quad&lt;-<span class="kw">data.frame</span>(<span class="dt">x=</span>x1,
                 <span class="dt">y=</span>y1)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(quad, <span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">theme_light</span>()</code></pre></div>
<p><img src="R4EH_book_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x, <span class="dt">data=</span>quad)
<span class="kw">summary</span>(reg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = quad)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.3498 -0.8570 -0.3221  0.4573 12.1560 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.43961    0.34604   12.83   &lt;2e-16 ***
## x           -0.08518    0.06763   -1.26    0.208    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.482 on 498 degrees of freedom
## Multiple R-squared:  0.003176,   Adjusted R-squared:  0.001174 
## F-statistic: 1.586 on 1 and 498 DF,  p-value: 0.2084</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">quadreg&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span><span class="kw">I</span>(x<span class="op">^</span><span class="dv">2</span>), <span class="dt">data=</span>quad)
<span class="kw">summary</span>(quadreg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + I(x^2), data = quad)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.51798 -0.32487  0.01175  0.33870  1.39794 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  28.22753    0.43975   64.19   &lt;2e-16 ***
## x           -10.05640    0.17820  -56.43   &lt;2e-16 ***
## I(x^2)        1.00407    0.01777   56.51   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5445 on 497 degrees of freedom
## Multiple R-squared:  0.8657, Adjusted R-squared:  0.8652 
## F-statistic:  1602 on 2 and 497 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(dplyr))
quad&lt;-quad <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">x2=</span>x<span class="op">^</span><span class="dv">2</span>,
         <span class="dt">x3=</span>x<span class="op">^</span><span class="dv">3</span>)

<span class="kw">head</span>(quad)</code></pre></div>
<pre><code>##          x        y       x2        x3
## 1 6.210004 4.668968 38.56415 239.48352
## 2 4.247019 3.831857 18.03717  76.60422
## 3 4.350733 3.239984 18.92888  82.35448
## 4 4.745756 3.405515 22.52220 106.88484
## 5 3.703630 4.782279 13.71688  50.80225
## 6 4.575343 2.538057 20.93376  95.77914</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">quadreg2&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>x2, <span class="dt">data=</span>quad)
<span class="kw">summary</span>(quadreg2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + x2, data = quad)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.51798 -0.32487  0.01175  0.33870  1.39794 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  28.22753    0.43975   64.19   &lt;2e-16 ***
## x           -10.05640    0.17820  -56.43   &lt;2e-16 ***
## x2            1.00407    0.01777   56.51   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5445 on 497 degrees of freedom
## Multiple R-squared:  0.8657, Adjusted R-squared:  0.8652 
## F-statistic:  1602 on 2 and 497 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Estimating marginal effects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">marginaleffect&lt;-<span class="cf">function</span>(x){
  quadreg<span class="op">$</span>coef[<span class="dv">2</span>]<span class="op">+</span><span class="dv">2</span><span class="op">*</span>quadreg<span class="op">$</span>coef[<span class="dv">3</span>]<span class="op">*</span>x
}
<span class="kw">marginaleffect</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>)</code></pre></div>
<pre><code>##  [1] -8.04826512 -6.04013174 -4.03199837 -2.02386500 -0.01573162
##  [6]  1.99240175  4.00053513  6.00866850  8.01680187 10.02493525</code></pre>
<div id="higher-polynomials" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Higher Polynomials</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cubicreg&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>x2<span class="op">+</span>x3, <span class="dt">data=</span>quad)
<span class="kw">summary</span>(cubicreg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + x2 + x3, data = quad)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.5223 -0.3211  0.0116  0.3374  1.3989 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 28.034692   1.102316  25.433  &lt; 2e-16 ***
## x           -9.922597   0.723542 -13.714  &lt; 2e-16 ***
## x2           0.974731   0.154766   6.298 6.65e-10 ***
## x3           0.002049   0.010738   0.191    0.849    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.545 on 496 degrees of freedom
## Multiple R-squared:  0.8658, Adjusted R-squared:  0.8649 
## F-statistic:  1066 on 3 and 496 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cubicreg2&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span><span class="kw">I</span>(x<span class="op">^</span><span class="dv">2</span>)<span class="op">+</span><span class="kw">I</span>(x<span class="op">^</span><span class="dv">3</span>), <span class="dt">data=</span>quad)
<span class="kw">summary</span>(cubicreg2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + I(x^2) + I(x^3), data = quad)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.5223 -0.3211  0.0116  0.3374  1.3989 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 28.034692   1.102316  25.433  &lt; 2e-16 ***
## x           -9.922597   0.723542 -13.714  &lt; 2e-16 ***
## I(x^2)       0.974731   0.154766   6.298 6.65e-10 ***
## I(x^3)       0.002049   0.010738   0.191    0.849    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.545 on 496 degrees of freedom
## Multiple R-squared:  0.8658, Adjusted R-squared:  0.8649 
## F-statistic:  1066 on 3 and 496 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cubicreg3&lt;-<span class="kw">lm</span>(y<span class="op">~</span><span class="kw">poly</span>(x,<span class="dv">3</span>, <span class="dt">raw=</span><span class="ot">TRUE</span>), <span class="dt">data=</span>quad)
<span class="kw">summary</span>(cubicreg3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ poly(x, 3, raw = TRUE), data = quad)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.5223 -0.3211  0.0116  0.3374  1.3989 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             28.034692   1.102316  25.433  &lt; 2e-16 ***
## poly(x, 3, raw = TRUE)1 -9.922597   0.723542 -13.714  &lt; 2e-16 ***
## poly(x, 3, raw = TRUE)2  0.974731   0.154766   6.298 6.65e-10 ***
## poly(x, 3, raw = TRUE)3  0.002049   0.010738   0.191    0.849    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.545 on 496 degrees of freedom
## Multiple R-squared:  0.8658, Adjusted R-squared:  0.8649 
## F-statistic:  1066 on 3 and 496 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Finding the maximum or minimum.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">min.x&lt;-(<span class="op">-</span><span class="fl">0.5</span><span class="op">*</span>quadreg<span class="op">$</span>coef[<span class="dv">2</span>]<span class="op">/</span>quadreg<span class="op">$</span>coef[<span class="dv">3</span>])
min.x</code></pre></div>
<pre><code>##        x 
## 5.007834</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># the predicted value of y at the minimum</span>
min.yhat&lt;-quadreg<span class="op">$</span>coef[<span class="dv">1</span>]<span class="op">+</span>quadreg<span class="op">$</span>coef[<span class="dv">2</span>]<span class="op">*</span>min.x<span class="op">+</span>quadreg<span class="op">$</span>coef[<span class="dv">3</span>]<span class="op">*</span>min.x
min.yhat</code></pre></div>
<pre><code>## (Intercept) 
##   -17.10504</code></pre>
<p><code>yhat</code> reaches a minimum of -17.11 when <code>x</code> is 5.01.</p>
<p><span class="math inline">\(F\)</span>-test of nonlinearity, <span class="math inline">\(H_0: \beta_2=\beta_3=0\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)</code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">linearHypothesis</span>(cubicreg, <span class="kw">c</span>(<span class="st">&quot;x2&quot;</span>,<span class="st">&quot;x3&quot;</span>))</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## x2 = 0
## x3 = 0
## 
## Model 1: restricted model
## Model 2: y ~ x + x2 + x3
## 
##   Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    498 1093.99                                  
## 2    496  147.34  2    946.66 1593.4 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="logarithmic-models" class="section level2">
<h2><span class="header-section-number">7.4</span> Logarithmic Models</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">quad&lt;-quad <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">l.x=</span><span class="kw">log</span>(x),
         <span class="dt">l.y=</span><span class="kw">log</span>(y))

<span class="kw">head</span>(quad)</code></pre></div>
<pre><code>##          x        y       x2        x3      l.x       l.y
## 1 6.210004 4.668968 38.56415 239.48352 1.826162 1.5409380
## 2 4.247019 3.831857 18.03717  76.60422 1.446217 1.3433495
## 3 4.350733 3.239984 18.92888  82.35448 1.470344 1.1755685
## 4 4.745756 3.405515 22.52220 106.88484 1.557251 1.2253962
## 5 3.703630 4.782279 13.71688  50.80225 1.309314 1.5649173
## 6 4.575343 2.538057 20.93376  95.77914 1.520682 0.9313989</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># linear log model</span>
lin_log_reg&lt;-<span class="kw">lm</span>(y<span class="op">~</span>l.x, <span class="dt">data =</span> quad)
<span class="kw">summary</span>(lin_log_reg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ l.x, data = quad)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.3562 -0.8767 -0.3256  0.4280 10.6428 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.3950     0.4952  12.914  &lt; 2e-16 ***
## l.x          -1.4960     0.3082  -4.854 1.62e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.451 on 498 degrees of freedom
## Multiple R-squared:  0.04518,    Adjusted R-squared:  0.04326 
## F-statistic: 23.56 on 1 and 498 DF,  p-value: 1.619e-06</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># log-linear model</span>
log_lin_reg&lt;-<span class="kw">lm</span>(l.y<span class="op">~</span>x, <span class="dt">data =</span> quad)
<span class="kw">summary</span>(log_lin_reg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = l.y ~ x, data = quad)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.82126 -0.18617 -0.03703  0.16323  1.44956 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.358081   0.072125  18.829   &lt;2e-16 ***
## x           -0.004126   0.014096  -0.293     0.77    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3089 on 498 degrees of freedom
## Multiple R-squared:  0.000172,   Adjusted R-squared:  -0.001836 
## F-statistic: 0.08567 on 1 and 498 DF,  p-value: 0.7699</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># log-log model</span>
log_log_reg&lt;-<span class="kw">lm</span>(l.y<span class="op">~</span>l.x, <span class="dt">data =</span> quad)
<span class="kw">summary</span>(log_log_reg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = l.y ~ l.x, data = quad)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.82359 -0.19326 -0.03528  0.15071  1.20178 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.68170    0.10432   16.12  &lt; 2e-16 ***
## l.x         -0.21616    0.06492   -3.33 0.000934 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3056 on 498 degrees of freedom
## Multiple R-squared:  0.02178,    Adjusted R-squared:  0.01981 
## F-statistic: 11.09 on 1 and 498 DF,  p-value: 0.0009342</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(stargazer))
<span class="kw">stargazer</span>(lin_log_reg, log_lin_reg, log_log_reg, <span class="dt">type=</span><span class="st">&quot;html&quot;</span>, <span class="dt">column.labels =</span> <span class="kw">c</span>(<span class="st">&quot;Linear-Log&quot;</span>, <span class="st">&quot;Log-Linear&quot;</span>, <span class="st">&quot;Log-Log&quot;</span>))</code></pre></div>
<table style="text-align:center">
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
y
</td>
<td colspan="2">
l.y
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
Linear-Log
</td>
<td>
Log-Linear
</td>
<td>
Log-Log
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
l.x
</td>
<td>
-1.496<sup>***</sup>
</td>
<td>
</td>
<td>
-0.216<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.308)
</td>
<td>
</td>
<td>
(0.065)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
x
</td>
<td>
</td>
<td>
-0.004
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.014)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
6.395<sup>***</sup>
</td>
<td>
1.358<sup>***</sup>
</td>
<td>
1.682<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.495)
</td>
<td>
(0.072)
</td>
<td>
(0.104)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
500
</td>
<td>
500
</td>
<td>
500
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.045
</td>
<td>
0.0002
</td>
<td>
0.022
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.043
</td>
<td>
-0.002
</td>
<td>
0.020
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error (df = 498)
</td>
<td>
1.451
</td>
<td>
0.309
</td>
<td>
0.306
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic (df = 1; 498)
</td>
<td>
23.564<sup>***</sup>
</td>
<td>
0.086
</td>
<td>
11.086<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="3" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<p>Interpretting the coefficients:</p>
<ul>
<li><strong>Linear-log model</strong>: a 1% change in <code>x</code> yields a -149.6 units change in <code>y</code></li>
<li><strong>Log-linear model</strong>: a 1 unit change in <code>x</code> yields a 0% change in <code>y</code></li>
<li><strong>Log-log model</strong>: a 1% change in <code>x</code> yields a -0.22% change in <code>y</code></li>
</ul>
</div>
<div id="standardizing-variables" class="section level2">
<h2><span class="header-section-number">7.5</span> Standardizing Variables</h2>
<p>Easiest way is to use the <code>scale()</code> command as part of the <code>mutate()</code> command in <code>dplyr</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gapminder)
gapminder&lt;-gapminder <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">s.life=</span><span class="kw">scale</span>(lifeExp),
         <span class="dt">s.gdp=</span><span class="kw">scale</span>(gdpPercap),
         <span class="dt">s.pop=</span><span class="kw">scale</span>(pop))

stdreg&lt;-<span class="kw">lm</span>(s.life<span class="op">~</span>s.gdp<span class="op">+</span>s.pop, <span class="dt">data=</span>gapminder)
<span class="kw">summary</span>(stdreg)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = s.life ~ s.gdp + s.pop, data = gapminder)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.4065 -0.5996  0.1591  0.6357  1.4348 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.038e-16  1.959e-02    0.00        1    
## s.gdp       5.858e-01  1.960e-02   29.89  &lt; 2e-16 ***
## s.pop       7.995e-02  1.960e-02    4.08 4.72e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8085 on 1701 degrees of freedom
## Multiple R-squared:  0.3471, Adjusted R-squared:  0.3463 
## F-statistic: 452.2 on 2 and 1701 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretting the coefficients:</p>
<ul>
<li>A 1 standard deviation change in <code>gdpPercap</code> yields a 0.59 standard deviation change in <code>lifeExp</code></li>
<li>A 1 standard deviation change in <code>pop</code> yields a 0.08 standard deviation change in <code>lifeExp</code></li>
</ul>
</div>
<div id="panel-data" class="section level2">
<h2><span class="header-section-number">7.6</span> Panel Data</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(df)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    500 obs. of  11 variables:
##  $ x     : num  8.75 10.37 8.33 13.19 10.66 ...
##  $ y     : num  265 348 228 517 236 ...
##  $ z     : num  15.3 16.8 13.8 19.5 11.2 ...
##  $ shape : Factor w/ 5 levels &quot;circle&quot;,&quot;rectangle&quot;,..: 4 5 3 1 4 4 3 1 2 4 ...
##  $ region: Factor w/ 4 levels &quot;east&quot;,&quot;north&quot;,..: 1 4 1 1 2 4 3 3 1 1 ...
##  $ yes   : num  0 1 0 0 1 0 1 1 0 0 ...
##  $ year  : Factor w/ 19 levels &quot;2000&quot;,&quot;2001&quot;,..: 10 2 17 9 19 10 18 1 4 8 ...
##  $ north : num  0 0 0 0 1 0 0 0 0 0 ...
##  $ south : num  0 0 0 0 0 0 1 1 0 0 ...
##  $ east  : num  1 0 1 1 0 0 0 0 1 1 ...
##  $ west  : num  0 1 0 0 0 1 0 0 0 0 ...</code></pre>
<p>Using <strong>Least Squares Dummy Variable (LSDV)</strong> approach</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_fe&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>region, <span class="dt">data =</span> df)
<span class="kw">summary</span>(reg_fe)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + region, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -133.702  -46.165   -5.717   49.537  120.099 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   -9.916     14.659  -0.676    0.499    
## x             31.333      1.331  23.536   &lt;2e-16 ***
## regionnorth  -11.107      8.031  -1.383    0.167    
## regionsouth  -12.089      7.968  -1.517    0.130    
## regionwest    -2.195      7.945  -0.276    0.782    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 60.02 on 495 degrees of freedom
## Multiple R-squared:  0.5287, Adjusted R-squared:  0.5249 
## F-statistic: 138.8 on 4 and 495 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>De-meaned Method using <code>plm</code> package</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(plm)</code></pre></div>
<pre><code>## Loading required package: Formula</code></pre>
<pre><code>## 
## Attaching package: &#39;plm&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     between, lag, lead</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_fe2&lt;-<span class="kw">plm</span>(y<span class="op">~</span>x, <span class="dt">data =</span> df, <span class="dt">index =</span> <span class="st">&quot;region&quot;</span>, <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>)
<span class="kw">summary</span>(reg_fe2)</code></pre></div>
<pre><code>## Oneway (individual) effect Within Model
## 
## Call:
## plm(formula = y ~ x, data = df, model = &quot;within&quot;, index = &quot;region&quot;)
## 
## Unbalanced Panel: n = 4, T = 98-137, N = 500
## 
## Residuals:
##      Min.   1st Qu.    Median   3rd Qu.      Max. 
## -133.7025  -46.1652   -5.7171   49.5375  120.0992 
## 
## Coefficients:
##   Estimate Std. Error t-value  Pr(&gt;|t|)    
## x  31.3333     1.3313  23.536 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    3778400
## Residual Sum of Squares: 1783000
## R-Squared:      0.5281
## Adj. R-Squared: 0.52428
## F-statistic: 553.946 on 1 and 495 DF, p-value: &lt; 2.22e-16</code></pre>
<div id="two-way-fixed-effects" class="section level3">
<h3><span class="header-section-number">7.6.1</span> Two Way Fixed Effects</h3>
<p>LSDV method</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_2way_fe&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>region<span class="op">+</span>year, <span class="dt">data =</span> df)
<span class="kw">summary</span>(reg_2way_fe)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + region + year, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -144.498  -43.865   -3.377   49.134  127.820 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    5.271     20.281   0.260    0.795    
## x             30.875      1.356  22.775   &lt;2e-16 ***
## regionnorth  -11.198      8.199  -1.366    0.173    
## regionsouth  -11.487      8.156  -1.408    0.160    
## regionwest    -1.072      8.096  -0.132    0.895    
## year2001     -26.478     18.142  -1.459    0.145    
## year2002      -3.579     17.490  -0.205    0.838    
## year2003     -18.924     17.587  -1.076    0.282    
## year2004     -22.182     17.521  -1.266    0.206    
## year2005     -11.986     18.819  -0.637    0.524    
## year2006     -22.034     18.293  -1.205    0.229    
## year2007       3.143     18.147   0.173    0.863    
## year2008       2.870     18.262   0.157    0.875    
## year2009     -12.448     18.742  -0.664    0.507    
## year2010     -16.316     17.583  -0.928    0.354    
## year2011      -4.261     17.522  -0.243    0.808    
## year2012      -6.719     19.379  -0.347    0.729    
## year2013     -19.188     19.911  -0.964    0.336    
## year2014       5.420     18.326   0.296    0.768    
## year2015     -14.284     19.692  -0.725    0.469    
## year2016     -11.172     17.851  -0.626    0.532    
## year2017      -7.987     18.493  -0.432    0.666    
## year2018     -19.580     17.895  -1.094    0.274    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 60.39 on 477 degrees of freedom
## Multiple R-squared:  0.5402, Adjusted R-squared:  0.519 
## F-statistic: 25.47 on 22 and 477 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">states&lt;-<span class="kw">c</span>(<span class="st">&quot;AL&quot;</span>,<span class="st">&quot;AK&quot;</span>,<span class="st">&quot;AZ&quot;</span>,<span class="st">&quot;AR&quot;</span>,<span class="st">&quot;CA&quot;</span>,<span class="st">&quot;CO&quot;</span>,<span class="st">&quot;CT&quot;</span>,<span class="st">&quot;DE&quot;</span>,<span class="st">&quot;FL&quot;</span>,<span class="st">&quot;GA&quot;</span>,<span class="st">&quot;HI&quot;</span>,<span class="st">&quot;ID&quot;</span>,<span class="st">&quot;IL&quot;</span>,<span class="st">&quot;IN&quot;</span>,<span class="st">&quot;IA&quot;</span>,<span class="st">&quot;KS&quot;</span>,<span class="st">&quot;KY&quot;</span>,<span class="st">&quot;LA&quot;</span>,<span class="st">&quot;ME&quot;</span>,<span class="st">&quot;MD&quot;</span>,<span class="st">&quot;MA&quot;</span>,<span class="st">&quot;MI&quot;</span>,<span class="st">&quot;MN&quot;</span>,<span class="st">&quot;MS&quot;</span>,<span class="st">&quot;MO&quot;</span>,<span class="st">&quot;MT&quot;</span>,<span class="st">&quot;NE&quot;</span>,<span class="st">&quot;NV&quot;</span>,<span class="st">&quot;NH&quot;</span>,<span class="st">&quot;NJ&quot;</span>,<span class="st">&quot;NM&quot;</span>,<span class="st">&quot;NY&quot;</span>,<span class="st">&quot;NC&quot;</span>,<span class="st">&quot;ND&quot;</span>,<span class="st">&quot;OH&quot;</span>,<span class="st">&quot;OK&quot;</span>,<span class="st">&quot;OR&quot;</span>,<span class="st">&quot;PA&quot;</span>,<span class="st">&quot;RI&quot;</span>,<span class="st">&quot;SC&quot;</span>,<span class="st">&quot;SD&quot;</span>,<span class="st">&quot;TN&quot;</span>,<span class="st">&quot;TX&quot;</span>,<span class="st">&quot;UT&quot;</span>,<span class="st">&quot;VT&quot;</span>,<span class="st">&quot;VA&quot;</span>,<span class="st">&quot;WA&quot;</span>,<span class="st">&quot;WV&quot;</span>,<span class="st">&quot;WI&quot;</span>,<span class="st">&quot;WY&quot;</span>)

df&lt;-<span class="kw">data.frame</span>() <span class="co"># make empty dataframe</span>

<span class="co"># for each state, generate data, creates dataframe called df_&quot;state&quot; e.g. df_AL, df_AK, etc. </span>
<span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">unique</span>(states)){
  <span class="kw">assign</span>(<span class="kw">paste</span>(<span class="st">&quot;df&quot;</span>,i,<span class="dt">sep=</span><span class="st">&quot;_&quot;</span>),<span class="kw">data.frame</span>(<span class="dt">state=</span>i,
                <span class="dt">year=</span><span class="kw">seq</span>(<span class="dv">2000</span>,<span class="dv">2018</span>,<span class="dv">1</span>),
                <span class="dt">x=</span><span class="kw">rnorm</span>(<span class="dv">19</span>,<span class="dv">5</span>,<span class="dv">1</span>),
                <span class="dt">y=</span><span class="kw">rnorm</span>(<span class="dv">19</span>,<span class="dv">2</span><span class="op">*</span>(<span class="kw">rnorm</span>(<span class="dv">19</span>,<span class="dv">5</span>,<span class="dv">1</span>)),<span class="dv">1</span>)) <span class="co"># make y approx 2*x </span>
  )
}

<span class="co"># make list of state dataframes</span>
statedfs&lt;-<span class="kw">lapply</span>(<span class="kw">ls</span>(<span class="dt">pattern=</span><span class="st">&quot;df_&quot;</span>),get)

<span class="co"># combine state dataframes to df </span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(statedfs)){
  df&lt;-<span class="kw">rbind</span>(df,statedfs[[i]])
}

<span class="co"># remove all individual state dataframes, (e.g. &quot;df_AL&quot;) keep only &quot;df&quot;</span>
<span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>(<span class="dt">pattern=</span><span class="st">&quot;df_&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;plm&quot;</span>)
<span class="kw">pdim</span>(df, <span class="dt">index=</span><span class="kw">c</span>(<span class="st">&quot;state&quot;</span>,<span class="st">&quot;year&quot;</span>))</code></pre></div>
<pre><code>## Balanced Panel: n = 50, T = 19, N = 950</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_2way_fe&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x<span class="op">+</span>state<span class="op">+</span><span class="kw">factor</span>(year), <span class="dt">data=</span>df)
<span class="kw">summary</span>(reg_2way_fe)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x + state + factor(year), data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.6800 -1.4700 -0.0804  1.4517  6.7585 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      11.381998   0.696423  16.344   &lt;2e-16 ***
## x                -0.145891   0.073974  -1.972   0.0489 *  
## stateAL          -0.631120   0.714836  -0.883   0.3775    
## stateAR          -1.259768   0.714804  -1.762   0.0783 .  
## stateAZ          -0.407688   0.714868  -0.570   0.5686    
## stateCA          -0.307402   0.714781  -0.430   0.6673    
## stateCO          -0.752466   0.714726  -1.053   0.2927    
## stateCT          -1.308885   0.714850  -1.831   0.0674 .  
## stateDE          -1.278362   0.714668  -1.789   0.0740 .  
## stateFL          -1.474282   0.714921  -2.062   0.0395 *  
## stateGA          -0.884094   0.714773  -1.237   0.2165    
## stateHI          -0.332327   0.714717  -0.465   0.6421    
## stateIA          -0.595839   0.715165  -0.833   0.4050    
## stateID          -0.547163   0.715739  -0.764   0.4448    
## stateIL          -0.600631   0.714671  -0.840   0.4009    
## stateIN          -0.848554   0.714770  -1.187   0.2355    
## stateKS          -0.286170   0.716084  -0.400   0.6895    
## stateKY          -0.741245   0.715003  -1.037   0.3002    
## stateLA          -0.419623   0.715409  -0.587   0.5577    
## stateMA          -0.298273   0.715053  -0.417   0.6767    
## stateMD          -0.421651   0.714674  -0.590   0.5553    
## stateME          -0.225449   0.714923  -0.315   0.7526    
## stateMI          -0.323392   0.715337  -0.452   0.6513    
## stateMN          -1.409148   0.714844  -1.971   0.0490 *  
## stateMO           0.301812   0.714674   0.422   0.6729    
## stateMS          -0.894070   0.716129  -1.248   0.2122    
## stateMT          -0.401861   0.714677  -0.562   0.5741    
## stateNC          -0.068496   0.714933  -0.096   0.9237    
## stateND          -0.165348   0.715353  -0.231   0.8173    
## stateNE          -0.900076   0.714719  -1.259   0.2082    
## stateNH          -1.110596   0.714850  -1.554   0.1206    
## stateNJ          -1.243386   0.714667  -1.740   0.0822 .  
## stateNM          -1.040089   0.714855  -1.455   0.1460    
## stateNV          -0.617321   0.714782  -0.864   0.3880    
## stateNY          -1.373121   0.715528  -1.919   0.0553 .  
## stateOH          -1.073487   0.714691  -1.502   0.1334    
## stateOK           0.082996   0.715137   0.116   0.9076    
## stateOR          -0.076596   0.714784  -0.107   0.9147    
## statePA          -1.164706   0.714974  -1.629   0.1037    
## stateRI          -0.145688   0.715129  -0.204   0.8386    
## stateSC          -1.228907   0.715302  -1.718   0.0861 .  
## stateSD          -1.082405   0.715272  -1.513   0.1306    
## stateTN          -0.518475   0.715005  -0.725   0.4686    
## stateTX          -0.245084   0.714922  -0.343   0.7318    
## stateUT          -0.166157   0.714669  -0.232   0.8162    
## stateVA          -0.851774   0.714666  -1.192   0.2336    
## stateVT          -1.258232   0.714696  -1.761   0.0787 .  
## stateWA          -1.366209   0.716866  -1.906   0.0570 .  
## stateWI          -0.378345   0.716385  -0.528   0.5975    
## stateWV           0.264818   0.714670   0.371   0.7111    
## stateWY          -1.193296   0.714766  -1.669   0.0954 .  
## factor(year)2001 -0.639847   0.441018  -1.451   0.1472    
## factor(year)2002 -0.206312   0.440886  -0.468   0.6399    
## factor(year)2003  0.272444   0.441398   0.617   0.5372    
## factor(year)2004  0.495971   0.441746   1.123   0.2618    
## factor(year)2005 -0.351603   0.440569  -0.798   0.4250    
## factor(year)2006  0.104295   0.440831   0.237   0.8130    
## factor(year)2007 -0.181204   0.440577  -0.411   0.6810    
## factor(year)2008 -0.109937   0.441432  -0.249   0.8034    
## factor(year)2009  0.071643   0.440802   0.163   0.8709    
## factor(year)2010  0.077712   0.440860   0.176   0.8601    
## factor(year)2011  0.008026   0.440651   0.018   0.9855    
## factor(year)2012 -0.127856   0.440794  -0.290   0.7718    
## factor(year)2013 -0.067184   0.440720  -0.152   0.8789    
## factor(year)2014 -0.257845   0.440685  -0.585   0.5586    
## factor(year)2015 -0.038034   0.440549  -0.086   0.9312    
## factor(year)2016  0.096685   0.441123   0.219   0.8266    
## factor(year)2017  0.094541   0.441374   0.214   0.8304    
## factor(year)2018 -0.778523   0.441417  -1.764   0.0781 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.203 on 881 degrees of freedom
## Multiple R-squared:  0.06812,    Adjusted R-squared:  -0.003807 
## F-statistic: 0.9471 on 68 and 881 DF,  p-value: 0.5995</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_2way_fe2&lt;-<span class="kw">plm</span>(y<span class="op">~</span>x, <span class="dt">data=</span>df, <span class="dt">index=</span><span class="kw">c</span>(<span class="st">&quot;state&quot;</span>,<span class="st">&quot;year&quot;</span>), <span class="dt">model=</span><span class="st">&quot;within&quot;</span>, <span class="dt">effect=</span><span class="st">&quot;twoways&quot;</span>)
<span class="kw">summary</span>(reg_2way_fe2)</code></pre></div>
<pre><code>## Twoways effects Within Model
## 
## Call:
## plm(formula = y ~ x, data = df, effect = &quot;twoways&quot;, model = &quot;within&quot;, 
##     index = c(&quot;state&quot;, &quot;year&quot;))
## 
## Balanced Panel: n = 50, T = 19, N = 950
## 
## Residuals:
##      Min.   1st Qu.    Median   3rd Qu.      Max. 
## -5.679977 -1.470018 -0.080427  1.451664  6.758480 
## 
## Coefficients:
##    Estimate Std. Error t-value Pr(&gt;|t|)  
## x -0.145891   0.073974 -1.9722   0.0489 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    4293.6
## Residual Sum of Squares: 4274.7
## R-Squared:      0.0043955
## Adj. R-Squared: -0.07245
## F-statistic: 3.88952 on 1 and 881 DF, p-value: 0.048901</code></pre>

</div>
</div>
</div>






            </section>

          </div>
        </div>
      </div>
<a href="regression-basics.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["R4EH_book.pdf", "R4EH_book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
