---
title: "Statement of Teaching Philosophy"
author: "Ryan Safner"
format: pdf
---

# Overview

The primary reason I decided on a career in academia was my passion for teaching and discussing economics. I remember how I was enticed into the social sciences (and specifically economics) by the passionate and inspiring teachers that I had as a student. I try to channel the energy and passion that got me into this profession in the first place, and inspire my students. I focus on four main pedagogical aspects of my teaching: skill-building, application and discussion, holistic assessment, and accessible resources and use of technology.

My main goal for all of my students is to appreciate economics as a *way of thinking* about the world, not a set of (mundane) topics like labor markets, stock prices, or inflation rates. I tell my students that "I am not a 9-to-5 economist," that is, I don't stop thinking like an economist when I leave work; economics to me is a lens to analyze and make our complex world more intelligible.

In my view, economics is a liberal art that instills a critical thinking mindset and provides a set of tools for approaching complex problems in the social world. I recognize that not every student is going to earn a Ph.D in economics, or even work in the field, and thus I optimize my courses to match student needs, and show them that economics can be useful regardless of whether they go into business, government, academia, non-profits, think tanks, or nearly any line of work. My overall goal is to take each student --- whatever their background, experience with economics, and future goals --- and make a significant *improvement* in their capabilities and skills, and spark their interest. I focus on building students' economic intuitions and their communication skills to help them in whatever career direction they embark on after college. Many students take some of my courses (particularly ECON 306, a requirement for all Business and Economics majors, taught every semester) to satisfy a requirement. The content of these theory courses can be difficult and mathematical. Students regularly describe in my course evaluations that these classes are hard and technical, but that I make it enjoyable and they come away having demonstrably learned a lot. Many students, including non-majors choose to take additional economics electives courses with me as a result, which they also emphasize in course evaluations.

I engage my students in learning by doing, as I firmly believe that the only way to truly understand something is to grapple with it in writing or in active discussion. More technical concepts, such as research and data analysis, require learning the actual tools of the trade (i.e. industry-level software and techniques, such as using R, markdown, and modern econometric models) and guiding students through the process of research and analysis from inspiration to a deliverable.

# Application and Discussion

I invite my students to be active participants in the process of understanding our world. I view successful instruction not as a mere "transfer of knowledge" from "master" to "apprentice", but an open invitation to joint inquiry. While several of my courses are required theory courses, or contain models and theoretical frameworks that require significant deliberate lecturing, I try to focus as much as possible on applications and letting my students discuss their interpretations and understanding of the world based on our course content. This is particularly true in my elective courses, where I feature a significant discussion component. I bring students to the "cutting edge" of the profession and engage them in current debates in the field --- meaning I give them more interesting questions to discuss rather than "the answer" --- whether they be about current events, or active disagreements between scholars or theoretical frameworks. For example, in my International Trade course (ECON 324), we discuss the economics of immigration, the social consequences of neoliberalism & free trade, and how these things translate into the recent electoral results. In my Public Economics course (ECON 410), we discuss a wide range of student-chosen issues from Blockchain technology to the Sharing Economy to Net Neutrality to Basic Income Guarantees. In Economics of Development (ECON 317), we wade through debates about the efficacy of foreign aid, and disagreements about the role of geography, culture, history, and institutions play in the disparity in economic development around the world.

Class participation is a significant (20-30%) portion of students' overall course grade in these electives, and I grade them on both their contributions to in-class discussion, and also on questions/discussion points based on our assigned readings that they email me prior to the discussion. This latter portion is designed both to incentivize students to do the readings (and not to just talk without doing the readings) and to reduce the penalty to quieter students who do not feel comfortable talking each day. Students often tell me or write in their evaluations that discussions were one of their favorite parts of my courses, even students that are quiet and still struggling to get out of their shell.

# Holistic Assessment of Students

While I recognize that grades are important (and most students view them as the *sine qua non* of a course), I provide multiple avenues for students to demonstrate their understanding of course materials. I care not about rote memorization of facts or what year Adam Smith wrote the *Wealth of Nations* but whether students are developing their critical thinking abilities using the economic way of thinking, and also their communication skills. In nearly all of my elective courses, I opt for a variety of writing-based assignments instead of formal exams. Where I do give an exam, they are often in-depth take-home essay questions. This again focuses on students internalizing the material and developing (and demonstrating) their ability to digest complex ideas coherently and build a reasonable argument with them.

Much of the content that I regularly teach (ECON 306, ECON 480) is quite challenging and mathematical. ECON 306 is among the most difficult courses that all Business majors are required to take; ECON 480 is certainly the same for Economics majors. Following advice from my department colleagues, I allow students to "correct" their exams: Students are allowed to redo questions for which they lost points by describing on another piece of paper what the correct answer is, and more importantly, *why* the answer is correct. This not only allows marginal students to avoid poor grades in required courses, but allows students to *internalize* the material and demonstrate to me their progress in mastering the subject area. I have also, from consultation of my colleagues, decided to grade homeworks based on a combination of completeness (70%) and accuracy (30% of one randomly-chosen problem). This encourages students to try their best and attempt each problem, but not stress about each and every problem being correct and fearing a low grade (not to mention, it's also easier for me and my Teaching Assistants to grade 20-30 assignments).

I assign multiple different types of assignment throughout the semester, ranging between problem sets, writing assignments, exams, and in-class discussion. Every single class I teach contains a writing assignment of some magnitude --- whether short papers, an Opinion-Editorial, or a research paper. I am very fond of the E. M. Forester quote "How can I know what I think until I see what I say?" I explain to students that one cannot truly internalize and understand a complex idea until one grapples with it enough to be able to craft an argument about it verbally or in writing. I ensure students know that this includes, notably, myself. I have learned *an enormous* amount from teaching and from writing about ideas, and proudly share that I have changed my mind on some issues from writing, reading, and discussing them with others. I also spend class time in ECON 306 and ECON 480 discussing how to write a good paper, sharing several guides and presentations that I have developed for this purpose.

A favorite assignment of mine is the empirical research paper project in econometrics. I require students to come up with a research question that they test by finding real world data, cleaning it, analyzing it, and writing up and presenting their results in a paper and accompanying presentation to the class. Rather than have students play with pre-cleaned "toy data" that has been sterilized for textbooks, students are exposed to the real world of "data wrangling" and analysis that real data scientists and empirical researchers experience in their day-to-day work. Furthermore, I make this a "high impact practice" by scaffolding this assignment so that students first submit ideas, then describe their data, then write a short literature review, then present their projects so far, and finally submit their written report. At each stage, I give feedback and provide suggestions to improve their projects. By the end, the students have remarkable work products that they can be proud of; many of them expand upon this very paper in their Senior Seminar in Economics, Departmental Honors papers for Economics, and one student has even published their paper.

Another innovative assignment that I created was a tournament for the "Most Interesting Economist in History," used in my History of Economic Thought course. Modeled on the NCAA March Madness tournament, I had students vote on whom they thought were more interesting (and write up their reasons) in a bracket of head-to-head matchups between economic writers that we read. Students found this a helpful and entertaining way to remember and compare an otherwise unwieldy list of several dozen writers. I wrote up my experience and the pedagogical value of this assignment in an article that is currently under review at a scholarly teaching journal.

# Technology and Accessible Resources

I am a major advocate of using technology in and out of the classroom, and someone who tries my hardest to give a wide range of students every opportunity to succeed. I do this by incorporating a wide variety of resources to assist students beyond mere textbook readings and homework problems. All my course materials (lectures, slides, homeworks, etc) are materials I that have made and disseminated myself (informed by textbooks or several academic sources, of course) - I have never used "stock" textbook powerpoints.

I always try to ensure that my courses are accessible to students in more ways than one. In terms of affordability, I eschew \$200-300 textbooks in favor of open source alternatives or I personally compile a list of key journal articles or popular books and applications for students to read or buy on Amazon for \$20-30. I also try to make the *material* accessible to students by frequently incorporating clips from movies and TV shows ranging between *The Wire*, *Monty Python*, and *Silicon Valley* to demonstrate concepts like black markets, price elasticity, constitutional design, and patent trolls.

We simulate double auction markets in Microeconomic Analysis using a platform called [Kiviq](http://kiviq.us): students are randomly assigned to be "Buyers" or "Sellers" who are randomly given "Valuations" and "Costs," respectively, for a fictional asset. They then must make bids and asks for prices to buy and sell, and ultimately we see these converge to a market-clearing equilibrium price where Supply meets Demand. In my Game Theory course, we played about a dozen or more games over the semester on [Moblab](http://moblab.com) to get hands-on experience in thinking about the strategy and incentives of prisoners' dilemmas, coordination games, Cournot, Bertrand, and Stackelberg-competition, and other types of games.

As someone who loves the world of coding, applications, and technologically-induced convenience, I tried to apply these tools to my courses wherever possible. I have written a variety of guides for my theory classes, particularly ECON 306 and ECON 480 --- ranging from handouts on mathematical concepts and models, to cheatsheets and guides to using statistical packages in `Stata` and `R` to accomplish a wide variety of tasks. Over the summers of 2018 and 2019, I learned `R`, a leading programming language for data science, to use in my econometrics course each Fall. For Summer 2019, I received an Academic Innovation grant to produce additional `R` resources for students. I have coded visualizations for students of key concepts in Microeconomics and Econometrics using `R` and `Shiny`, which allow for students to tangibly and intuitively *see* how changing certain parameters will affect the outcomes of the model. Since Fall 2019 semester, I personally coded course websites for each of my courses to act as a platform for all course content (lecture slides, assignments, readings, tools & links, etc) in one accessible location. This fortuitously made the transition to online teaching during the Covid-19 pandemic quite easy for me. My colleagues have taken notice of my leading the charge with R and other software. One of my former, colleagues, Dr. Mel Zuberi, audited the Fall 2019 semester of my econometrics class in order to learn these techniques and software skills himself.

Finally, I strongly believe that teaching should be a positive externality on the world: not only should my *own* students benefit from learning and completing my courses, but anyone else who wants to should as well. By making my courses "open source" and sharing all major materials on the web, *anyone* can benefit from my materials for free, in addition to [my blogging](http://ryansafner.com/post/) about these subjects. I often am asked by friends and colleagues at academic conferences for some of my materials, or am happy to learn that a *colleague of a colleague* followed along with my lectures and materials in my econometrics course through my website.
